import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Type definitions (matching page.tsx)
type ApiResult = {
  transcription: string;
  summary: string;
  language: string;
  durationSec?: number;
  mom: { participants: string[]; decisions: string[]; actionItems: string[]; nextSteps: string[] };
  insights?: { sentiment?: string; sentimentScore?: number; topics?: string[]; keywords?: string[] };
  coaching?: {
    overallScore: number;
    categoryScores?: { opening: number; discovery: number; solutionPresentation: number; objectionHandling: number; closing: number; empathy: number; clarity: number; compliance: number };
    strengths: string[];
    weaknesses: string[];
    missedOpportunities: string[];
    customerHandling: { score: number; feedback: string };
    communicationQuality: { score: number; feedback: string };
    pitchEffectiveness: { score: number; feedback: string };
    objectionHandling: { score: number; feedback: string };
    forcedSale?: { detected: boolean; severity: 'none' | 'mild' | 'moderate' | 'severe'; indicators: string[]; feedback: string };
    improvementSuggestions: string[];
    scriptRecommendations: string[];
    redFlags: string[];
    coachingSummary: string;
  };
  conversationMetrics?: {
    agentTalkRatio: number; customerTalkRatio: number; silenceRatio: number;
    totalQuestions: number; openQuestions: number; closedQuestions: number;
    agentInterruptions: number; customerInterruptions: number;
    avgResponseTimeSec: number; longestPauseSec: number;
    wordsPerMinuteAgent: number; wordsPerMinuteCustomer: number;
  };
  conversationSegments?: { name: string; startTime: string; endTime: string; durationSec: number; quality: string; notes: string }[];
  keyMoments?: { timestamp: string; type: string; speaker: string; text: string; sentiment: string; importance: string }[];
  predictions?: { conversionProbability: number; churnRisk: string; escalationRisk: string; satisfactionLikely: string; followUpNeeded: boolean; urgencyLevel: string };
  customerProfile?: { communicationStyle: string; decisionStyle: string; engagementLevel: string; pricesSensitivity: string; concerns: string[]; preferences: string[] };
  actionItems?: { forAgent: string[]; forManager: string[]; forFollowUp: string[] };
};

type BulkCallResult = { 
  id: string; 
  fileName: string; 
  fileSize: number; 
  status: 'pending' | 'processing' | 'completed' | 'error'; 
  result?: ApiResult; 
  error?: string;
  audioUrl?: string;
};

// Helper to format duration
const formatDuration = (seconds: number) => {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

// Helper to add a section title
const addSectionTitle = (doc: jsPDF, title: string, y: number) => {
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, y);
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y + 2, 196, y + 2);
  return y + 10;
};

// Helper to get score color
const getScoreColor = (score: number): [number, number, number] => {
  if (score >= 80) return [22, 163, 74]; // Green
  if (score >= 60) return [234, 179, 8]; // Yellow
  return [220, 38, 38]; // Red
};

// --- Single Call Report ---
export const generateCallAnalysisPDF = (call: BulkCallResult) => {
  if (!call.result) return;
  
  const result = call.result;
  const fileName = call.fileName;
  const doc = new jsPDF();
  let yPos = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(59, 130, 246); // Blue
  doc.text("Call Analysis Report", 14, yPos);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by CallTranscribe AI`, 14, yPos + 6);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 160, yPos + 6);
  yPos += 20;

  // 1. Overview
  yPos = addSectionTitle(doc, "Overview", yPos);
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.setFont('helvetica', 'normal');
  
  const overviewData = [
    ['File Name', fileName],
    ['Duration', formatDuration(result.durationSec || 0)],
    ['Language', result.language || 'Unknown'],
    ['Overall Score', `${result.coaching?.overallScore || 0}/100`],
    ['Sentiment', `${result.insights?.sentiment || 'Neutral'}`],
    ['Conversion Prob.', `${result.predictions?.conversionProbability || 0}%`],
  ];

  autoTable(doc, {
    startY: yPos,
    body: overviewData,
    theme: 'plain',
    styles: { cellPadding: 1, fontSize: 10 },
    columnStyles: { 0: { fontStyle: 'bold', width: 40 } },
  });
  yPos = (doc as any).lastAutoTable.finalY + 10;

  // 2. Summary
  yPos = addSectionTitle(doc, "Executive Summary", yPos);
  const summaryLines = doc.splitTextToSize(result.summary, 180);
  doc.text(summaryLines, 14, yPos);
  yPos += (summaryLines.length * 5) + 10;

  // 3. Metrics Table
  yPos = addSectionTitle(doc, "Conversation Metrics", yPos);
  const metrics = result.conversationMetrics;
  
  if (metrics) {
    const metricsData = [
      ['Agent Talk Ratio', `${metrics.agentTalkRatio || 0}%`, 'Avg Response Time', `${metrics.avgResponseTimeSec?.toFixed(1) || 0}s`],
      ['Customer Talk Ratio', `${metrics.customerTalkRatio || 0}%`, 'Agent WPM', `${metrics.wordsPerMinuteAgent || 0}`],
      ['Silence Ratio', `${metrics.silenceRatio || 0}%`, 'Customer WPM', `${metrics.wordsPerMinuteCustomer || 0}`],
      ['Agent Interruptions', `${metrics.agentInterruptions || 0}`, 'Total Questions', `${metrics.totalQuestions || 0}`],
      ['Cust Interruptions', `${metrics.customerInterruptions || 0}`, 'Longest Pause', `${metrics.longestPauseSec?.toFixed(1) || 0}s`],
    ];

    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value', 'Metric', 'Value']],
      body: metricsData,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
      styles: { fontSize: 9 },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(10);
    doc.text('No conversation metrics available', 14, yPos);
    yPos += 10;
  }

  // 4. Coaching Scores
  if (yPos > 240) { doc.addPage(); yPos = 20; }
  yPos = addSectionTitle(doc, "Coaching & Scores", yPos);
  
  const coaching = result.coaching;
  if (coaching) {
    // Overall score highlight
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    const [r, g, b] = getScoreColor(coaching.overallScore);
    doc.setTextColor(r, g, b);
    doc.text(`Overall Score: ${coaching.overallScore}/100`, 14, yPos);
    yPos += 8;
    
    // Category scores
    const scores = coaching.categoryScores;
    if (scores) {
      const scoreData = Object.entries(scores).map(([key, val]) => [
        key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
        val
      ]);

      autoTable(doc, {
        startY: yPos,
        head: [['Category', 'Score (0-100)']],
        body: scoreData,
        theme: 'striped',
        headStyles: { fillColor: [16, 185, 129] },
        styles: { fontSize: 9 },
        tableWidth: 100,
      });
      yPos = (doc as any).lastAutoTable.finalY + 5;
    }

    // Forced Sale Warning
    const forcedSale = coaching.forcedSale;
    if (forcedSale?.detected) {
      if (yPos > 240) { doc.addPage(); yPos = 20; }
      doc.setFillColor(254, 226, 226);
      doc.setDrawColor(239, 68, 68);
      doc.rect(14, yPos, 182, 30, 'FD');
      
      doc.setFontSize(11);
      doc.setTextColor(185, 28, 28);
      doc.setFont('helvetica', 'bold');
      doc.text('WARNING: Forced Sale Detected', 20, yPos + 8);
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Severity: ${forcedSale.severity.toUpperCase()}`, 20, yPos + 16);
      
      const reasonLines = doc.splitTextToSize(forcedSale.feedback || '', 170);
      doc.text(reasonLines.slice(0, 2), 20, yPos + 22);
      yPos += 35;
    }
  }
  
  yPos += 10;

  // 5. Strengths & Weaknesses
  if (yPos > 230) { doc.addPage(); yPos = 20; }
  
  const strengths = result.coaching?.strengths || [];
  const weaknesses = result.coaching?.weaknesses || [];
  
  if (strengths.length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129);
    doc.text('Strengths:', 14, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    strengths.forEach((s) => {
      yPos += 5;
      if (yPos > 280) { doc.addPage(); yPos = 20; }
      const lines = doc.splitTextToSize(`• ${s}`, 180);
      doc.text(lines, 14, yPos);
      yPos += (lines.length - 1) * 4;
    });
    yPos += 8;
  }
  
  if (weaknesses.length > 0) {
    if (yPos > 250) { doc.addPage(); yPos = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(239, 68, 68);
    doc.text('Areas for Improvement:', 14, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    weaknesses.forEach((w) => {
      yPos += 5;
      if (yPos > 280) { doc.addPage(); yPos = 20; }
      const lines = doc.splitTextToSize(`• ${w}`, 180);
      doc.text(lines, 14, yPos);
      yPos += (lines.length - 1) * 4;
    });
  }

  yPos += 15;

  // 6. Key Moments
  const keyMoments = result.keyMoments || [];
  if (keyMoments.length > 0) {
    if (yPos > 220) { doc.addPage(); yPos = 20; }
    yPos = addSectionTitle(doc, "Key Moments", yPos);

    const momentsData = keyMoments.slice(0, 10).map((m) => [
      m.timestamp || '-',
      (m.type || '').replace(/_/g, ' ').toUpperCase(),
      m.speaker || '-',
      m.sentiment || '-',
      (m.text || '').substring(0, 50) + ((m.text || '').length > 50 ? '...' : '')
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Time', 'Type', 'Speaker', 'Sentiment', 'Text snippet']],
      body: momentsData,
      theme: 'grid',
      styles: { fontSize: 8 },
      columnStyles: { 4: { cellWidth: 'auto' } },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  // 7. Action Items
  const actions = result.actionItems;
  if (actions) {
    if (yPos > 240) { doc.addPage(); yPos = 20; }
    yPos = addSectionTitle(doc, "Action Items", yPos);
    
    const allActions = [
      ...(actions.forAgent || []).map((a: string) => `[Agent] ${a}`),
      ...(actions.forManager || []).map((a: string) => `[Manager] ${a}`),
      ...(actions.forFollowUp || []).map((a: string) => `[Follow-up] ${a}`),
    ];

    if (allActions.length > 0) {
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      allActions.forEach((item) => {
        yPos += 6;
        if (yPos > 280) { doc.addPage(); yPos = 20; }
        const lines = doc.splitTextToSize(`□ ${item}`, 180);
        doc.text(lines, 14, yPos);
        yPos += (lines.length - 1) * 4;
      });
    } else {
      doc.text('No action items recorded', 14, yPos);
    }
  }

  // Footer (Page Numbers)
  const pageCount = (doc as any).internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, 196, 290, { align: 'right' });
  }

  doc.save(`CallAnalysis_${fileName.replace(/\.[^/.]+$/, "")}.pdf`);
};


// --- Bulk Report ---
export const generateBulkAnalysisPDF = (results: BulkCallResult[]) => {
  const doc = new jsPDF();
  let yPos = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(59, 130, 246);
  doc.text("Bulk Call Analysis Report", 14, yPos);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Date: ${new Date().toLocaleDateString()} | Total Calls: ${results.length}`, 14, yPos + 7);
  yPos += 20;

  // Calculate Aggregates
  const completed = results.filter(r => r.status === 'completed' && r.result);
  const avgScore = completed.reduce((acc, curr) => acc + (curr.result?.coaching?.overallScore || 0), 0) / (completed.length || 1);
  const totalRedFlags = completed.reduce((acc, curr) => acc + (curr.result?.coaching?.redFlags?.length || 0), 0);
  const forcedSales = completed.filter(r => r.result?.coaching?.forcedSale?.detected).length;

  // Aggregate Stats Box
  doc.setFillColor(240, 249, 255);
  doc.rect(14, yPos, 182, 25, 'F');
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(`Calls Analyzed: ${completed.length}`, 20, yPos + 10);
  doc.text(`Average Score: ${avgScore.toFixed(1)}/100`, 80, yPos + 10);
  doc.text(`Total Red Flags: ${totalRedFlags}`, 140, yPos + 10);
  
  doc.setTextColor(185, 28, 28);
  doc.text(`Forced Sales Detected: ${forcedSales}`, 20, yPos + 20);
  yPos += 35;

  // Main Table
  const tableData = results.map(r => {
    if (r.status !== 'completed' || !r.result) {
      return [r.fileName.substring(0, 35), 'Failed/Pending', '-', '-', '-'];
    }
    const res = r.result;
    return [
      r.fileName.substring(0, 35),
      `${res.coaching?.overallScore || 0}`,
      res.insights?.sentiment || 'N/A',
      `${res.predictions?.conversionProbability || 0}%`,
      (res.coaching?.forcedSale?.detected ? 'YES' : 'No')
    ];
  });

  autoTable(doc, {
    startY: yPos,
    head: [['File Name', 'Score', 'Sentiment', 'Conv. Prob', 'Forced Sale?']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 65 },
      1: { halign: 'center', cellWidth: 20 },
      2: { halign: 'center', cellWidth: 25 },
      3: { halign: 'center', cellWidth: 25 },
      4: { halign: 'center', cellWidth: 25 }
    },
    didParseCell: (data: any) => {
      if (data.section === 'body' && data.column.index === 4) {
        if (data.cell.raw === 'YES') {
          data.cell.styles.textColor = [185, 28, 28];
          data.cell.styles.fontStyle = 'bold';
        } else {
          data.cell.styles.textColor = [0, 0, 0];
          data.cell.styles.fontStyle = 'normal';
        }
      }
    }
  });
  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Common Strengths & Weaknesses Summary
  const allStrengths = completed.flatMap(r => r.result?.coaching?.strengths || []);
  const allWeaknesses = completed.flatMap(r => r.result?.coaching?.weaknesses || []);
  
  const countFreq = (arr: string[]) => {
    const freq: Record<string, number> = {};
    arr.forEach(item => { const key = item.toLowerCase().trim(); freq[key] = (freq[key] || 0) + 1; });
    return Object.entries(freq).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([k]) => k);
  };

  if (yPos > 220) { doc.addPage(); yPos = 20; }
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 185, 129);
  doc.text('Common Team Strengths:', 14, yPos);
  yPos += 6;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  countFreq(allStrengths).forEach(s => {
    yPos += 5;
    doc.text(`• ${s}`, 14, yPos);
  });
  
  yPos += 12;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text('Common Areas for Improvement:', 14, yPos);
  yPos += 6;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  countFreq(allWeaknesses).forEach(w => {
    yPos += 5;
    doc.text(`• ${w}`, 14, yPos);
  });

  // Footer (Page Numbers)
  const pageCount = (doc as any).internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 196, 290, { align: 'right' });
    doc.text('CallTranscribe - Bulk Analysis Report', 14, 290);
  }

  doc.save(`BulkAnalysis_${new Date().toISOString().slice(0,10)}.pdf`);
};
